### ISSUE TITLE
다음과 같은 디렉터리 구조가 나오도록 해주세요.

### ISSUE THREAD

**Issue by AnByoungHyun** [AnByoungHyun/mysite#1]
## Django 기본 디렉터리 구조 만들어 두기

아래의 구조와 같은 형태로 Django Project의 디렉터리 및 파일 구조를 만들어 주세요.

<hr>

- mysite/
  - settings.py
  - urls.py
  - wsgi.py
- static/
  - bootstrap/
    - css/
      - bootstrap.css
      - bootstrap.css.map
      - 각종 Bootstrap 파일들...
    - js/
      - bootstrap.bundle.js
      - bootstrap.bundle.js.map
      - 각종 Bootstrap 파일들...
  - base/
    - images/
- templates/
- manage.py
- README.md
- requirements.txt

<hr>

Bootstrap은 4.5.x 버전을 [다운로드](https://getbootstrap.com/docs/4.5/getting-started/download/) 받아서 사용을 하면 됩니다. 

Compiled CSS and JS 에서 다운받으세요.

위 작업을 진행 할 때 클론(Clone) 작업으로 진행하세요.

``` bash
git clone https://github.com/AnByoungHyun/mysite.git
git checkout <브랜치명>
```

**Comment by suhyun226** [comment]
빈 폴더(templates)를 어떻게  remote repository로 push 하나요?
local repository에는 add로 만들었습니다

**Comment by AnByoungHyun** [comment]
빈 디렉터리에 대해서는 GIT이 추적관리 하지 않기 때문에 빈 디렉터리에 빈 파일을 생성하여 추적이 되도록 하면 됩니다.

**Comment by wjdqudwo** [comment]
aaaa
